version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies and setting up Docker"
      - mkdir -p /var/www/html
      - echo "Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 &>/var/log/docker.log &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"

  pre_build:
    commands:
      - echo "Preparing build environment..."
      - cp -r $CODEBUILD_SRC_DIR/* /var/www/html/
      - chmod -R 755 /var/www/html
      - cd /var/www/html
      - echo "Creating or verifying Docker network 'twotier'"
      - docker network create twotier || echo "Network already exists"
      - echo "Cleaning up any old containers..."
      - docker rm -f mysql1 || true
      - docker rm -f newflaskapp || true

  build:
    commands:
      - echo "Building Flask app image..."
      - docker build -t flaskapp .
      - echo "Cleaning old MySQL container..."
      - docker rm -f mysql1 || true
      - docker pull mysql:5.7
      - echo "Starting MySQL container..."
      - docker run -d -p 3306:3306 --network=twotier -e MYSQL_DATABASE=mydb -e MYSQL_USER=admin -e MYSQL_PASSWORD=admin -e MYSQL_ROOT_PASSWORD=admin --name=mysql1 mysql:5.7
      - echo "Waiting for MySQL to initialize..."
      - sleep 25
      - echo "Starting Flask container..."
      - docker run -d -p 5000:5000 --network=twotier -e MYSQL_HOST=mysql1 -e MYSQL_USER=admin -e MYSQL_PASSWORD=admin -e MYSQL_DB=mydb --name=newflaskapp flaskapp:latest

  post_build:
    commands:
      - echo "Build and container startup complete!"
      - docker ps
      - docker logs mysql11 || true
      - docker logs newflaskapp || true

artifacts:
  files:
    - '/var/www/html/**/*'
  discard-paths: no
